---
- hosts: dbserver 
  tasks: 
    - name: Adicionar usuario developer nos servidores 
      become: true
      user: name=developer state=present shell=/bin/bash password=$1$q0jaPRhm$WZaoeXzWa2NSMlaDKkO5q0